In [1]:
import numpy as np
import numpy.linalg as alg

In [28]:
A = np.matrix([[36,1,3],[1,45,-3],[3,-3,27]])
print(A)
print(alg.det(A))

[[36  1  3]
 [ 1 45 -3]
 [ 3 -3 27]]
42966.00000000001


In [31]:
L = alg.cholesky(A)
LT = np.transpose(L)
print(A)
print(L)
print(LT)

[[36  1  3]
 [ 1 45 -3]
 [ 3 -3 27]]
[[ 6.          0.          0.        ]
 [ 0.16666667  6.70613318  0.        ]
 [ 0.5        -0.45977812  5.15156327]]
[[ 6.          0.16666667  0.5       ]
 [ 0.          6.70613318 -0.45977812]
 [ 0.          0.          5.15156327]]


In [32]:
A = np.matrix([[36,1,3],[1,45,-53],[3,-53,27]])
L = alg.cholesky(A)
LT = np.transpose(L)
print(A)
print(L)
print(LT)

LinAlgError: Matrix is not positive definite

In [33]:
A = np.matrix([[36,1],[1,45],[3,27]])
L = alg.cholesky(A)
LT = np.transpose(L)
print(A)
print(L)
print(LT)

LinAlgError: Last 2 dimensions of the array must be square

In [37]:
#EIGEN DECOMPOSITION
A = np.matrix([[36,1,3],[1,45,-3],[3,-3,27]])
eigv,eigvec = alg.eig(A)
print(eigv,end="\n\n")
print(eigvec,end="\n\n")
Pinv = alg.inv(eigvec)
D = np.diag(eigv)
print(D)

[25.57719281 36.90747311 45.51533409]

[[-0.28721094  0.95621873 -0.05617492]
 [ 0.16064174 -0.00973062 -0.98696482]
 [ 0.94430086  0.29249113  0.1508139 ]]

[[25.57719281  0.          0.        ]
 [ 0.         36.90747311  0.        ]
 [ 0.          0.         45.51533409]]


In [38]:
A = np.matrix([[36,1],[1,45],[3,27]])
eigv,eigvec = alg.eig(A)
print(eigv,end="\n\n")
print(eigvec,end="\n\n")
Pinv = alg.inv(eigvec)
D = np.diag(eigv)
print(D)

LinAlgError: Last 2 dimensions of the array must be square