In [1]:
import numpy as np
A = np.array([[1,2],
              [4,5]])
B = np.array([[6,2],
             [7,0]])
C = np.array([[1,2,5],
              [3,4,6]])

In [2]:
#Addition of A and B
print(A+B)
print(A+C)#dimension should be same

[[ 7  4]
 [11  5]]


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [4]:
#Multiplication of A and B
print(np.matmul(A,B))
#When CxA can't be done because of dimension 2x3 and 2x2
print(np.matmul(C,A))

[[20  2]
 [59  8]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [4]:
#Determinant of matrix A
np.linalg.det(A)

-2.9999999999999996

In [5]:
#Rank of matrix A
np.linalg.matrix_rank(A)

2

In [6]:
#Multiplicative inverse of A
np.linalg.inv(A)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [5]:
#Let D be a matrix of det = 0
D = np.matrix([[1,2],
               [2,4]])
print(np.linalg.det(D))
print(np.linalg.inv(D))#Inverse can't be found for matrix with det 0

0.0


LinAlgError: Singular matrix

In [3]:
"""Let two equations be a1x+b1y=c1 and a2x+b2y=c2
We know that in substitution we substitute a variable in 1 equation using other equation. By doing this we get the following
solution x = (c1b2-b2c1)/(a1b2-a2b1) and y = x = (a1c2-a2c1)/(a1b2-a2b1) and if denominator is infinity the lines are 
parallel"""
a1,b1,c1,a2,b2,c2 = map(int,input().split())
det = a1*b2 - b1*a2
if det==0:
    print("Lines are parallel")
else:
    x = (c1*b2 - b1*c2)/det
    y = (a1*c2 - c1*a2)/det
    print("Solution is x={} and y={}".format(x,y))

2 3 4 4 6 8
Lines are parallel


In [5]:
#Let two equations be a1x+b1y=c1 and a2x+b2y=c2
a1,b1,c1,a2,b2,c2 = map(int,input().split())
b1 = b1*a2
c1 = c1*a2
b2 = b2*a1
c2 = c2*a1
a1 = a1*a2
a2 = a1
if b1-b2==0:
    print("The lines are parallel")
else:
    y = (c1-c2)/(b1-b2)
    x = (c1 - b1*y)/(a1)
    print("Solution is x={} and y={}".format(x,y))

2 3 4 4 6 8
The lines are parallel


In [6]:
#Gauss Elimination Method: Every 1st element of the row should be the only non zero element in its column
import numpy as np
a = np.zeros((2,3))
x = np.zeros(2)
for i in range(2):#taking input of augmented matrix
    for j in range(3):
        a[i][j] = float(input())
print(a)
rat = a[1][0]/a[0][0]
for k in range(3):
    a[1][k]-=(rat*a[0][k])
print(a)
x[1] = a[1][2]/a[1][1]#finding the last variable because in matrix that can be caluclated only
x[0] = (a[0][2]-x[1]*a[0][1])/a[0][0]
print('\nSolution : %f and %f' %(x[0],x[1]))

2
3
14
4
6
10
[[ 2.  3. 14.]
 [ 4.  6. 10.]]
[[  2.   3.  14.]
 [  0.   0. -18.]]

Solution : inf and -inf


C:\Users\Somit Jain\AppData\Local\Temp\ipykernel_18032\2570181741.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  x[1] = a[1][2]/a[1][1]#finding the last variable because in matrix that can be caluclated only


In [7]:
#Gauss Jordan Elimination: There can be only one non zero element in each row and column
import numpy as np
a = np.zeros((2,3))
x = np.zeros(2)
for i in range(2):#taking input of augmented matrix
    for j in range(3):
        a[i][j] = float(input())
print(a)
rat1 = a[1][0]/a[0][0]
for k in range(3):
    a[1][k]-=(rat1*a[0][k])
rat2 = a[0][1]/a[1][1]
for k in range(3):
    a[0][k]-=(rat2*a[1][k])
print(a)
x[1] = a[1][2]/a[1][1]
x[0] = a[0][2]/a[0][0]
print('\nSolution : %f and %f' %(x[0],x[1]))

2
3
18
5
1
19
[[ 2.  3. 18.]
 [ 5.  1. 19.]]
[[  2.    0.    6. ]
 [  0.   -6.5 -26. ]]

Solution : 3.000000 and 4.000000


In [13]:
import numpy as np
a = np.ones((2,2))
b = np.zeros((2,1))
x = np.zeros(2)
for i in range(2):#taking input of augmented matrix
    a[i][0]= float(input())
    a[i][1]= float(input())
    b[i][0]= float(input())
print(a)
print(b)
np.linalg.solve(a,b)

2
3
4
4
6
8
[[2. 3.]
 [4. 6.]]
[[4.]
 [8.]]


LinAlgError: Singular matrix

In [15]:
import numpy as np
import numpy.linalg as alg
A = np.matrix([[1,2,3,4],
               [4,5,6,5],
               [7,8,9,6]])
evalu,evect = alg.eig(A)
evalu = np.round_(evalu)
evect = np.round_(evect)
print("Eigen Values:")
print(evalu)
print("Eigen Vectors:")
print(evect)

LinAlgError: Last 2 dimensions of the array must be square